Tresepic\BoprBundle\Entity\Banner:
    type: entity
    table: banner
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        priority:
            type: integer
            nullable: true
        imageName:
            type: string
            length: 255
        link:
            type: string
            lenght: 255
            nullable: true
        isSuscription:
            type: boolean
            nullable: true
        isEnabled:
            type: boolean
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    lifecycleCallbacks: {  }
