Tresepic\BoprBundle\Entity\Product:
    type: entity
    table: sylius_product
    fields:
        position:
            type: integer
            nullable: true
    manyToOne:
        manufacturer:
            targetEntity: Manufacturer
            inversedBy: products
            joinColumn:
                name: manufacturer_id
                referencedColumnName: id
                onDelete: SET NULL
    lifecycleCallbacks: {  }
