Tresepic\BoprBundle\Entity\Testimonial:
    type: entity
    table: testimonial
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        testimony:
            type: string
            length: 255
        author:
            type: string
            length: 255
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    lifecycleCallbacks: {  }
