imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sylius.yml }
    - { resource: payum.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

framework:
    translator:      { fallback: %sylius.locale% }
    secret:          %sylius.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%sylius.locale%"
    trusted_proxies: ~
    session:         ~

twig:
    form:
        resources:
            - 'SyliusWebBundle::forms.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        facebook_client_id: %sylius.oauth.facebook.clientid%
        facebook_scope: %sylius.oauth.facebook.scope%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['SyliusWebBundle']
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   %sylius.database.driver%
        host:     %sylius.database.host%
        port:     %sylius.database.port%
        dbname:   %sylius.database.name%
        user:     %sylius.database.user%
        password: %sylius.database.password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
        workspace: default
        username: admin
        password: admin
    odm:
        auto_mapping: true

stof_doctrine_extensions:
    default_locale: %sylius.locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true
            loggable: true
            sortable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: %sylius.model.user.class%
    group:
        group_class: Sylius\Bundle\CoreBundle\Model\Group
    profile:
        form:
            type: sylius_user_profile
    registration:
        form:
            type: sylius_user_registration

hwi_oauth:
    firewall_name: main
    resource_owners:
        facebook:
            type:          facebook
            client_id:     %sylius.oauth.facebook.clientid%
            client_secret: %sylius.oauth.facebook.clientsecret%
            scope:         %sylius.oauth.facebook.scope%
        twitter:
            type:          twitter
            client_id:     %sylius.oauth.twitter.clientid%
            client_secret: %sylius.oauth.twitter.clientsecret%

swiftmailer:
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%

liip_doctrine_cache:
    namespaces:
        sylius_settings: %sylius.cache%

knp_gaufrette:
    adapters:
        sylius_image:
            local:
                directory:  %kernel.root_dir%/../web/media/image
                create:     true
    filesystems:
        sylius_image:
            adapter: sylius_image

liip_imagine:
    data_root: %kernel.root_dir%/../web/media/image
    filter_sets:
        sylius_16x16:
            filters:
                thumbnail: { size: [16, 16], mode: outbound }
        sylius_50x40:
            filters:
                thumbnail: { size: [50, 40], mode: outbound }
        sylius_90x60:
            filters:
                thumbnail: { size: [90, 60], mode: outbound }
        sylius_400x400:
            filters:
                thumbnail: { size: [400, 400], mode: outbound }

        sylius_262x255:
            filters:
                thumbnail: { size: [265, 255], mode: outbound }
        sylius_250x250:
            filters:
                thumbnail: { size: [250, 250], mode: outbound }
        sylius_310x300:
            filters:
                thumbnail: { size: [310, 300], mode: outbound }
        sylius_610x600:
            filters:
                thumbnail: { size: [610, 600], mode: outbound }
        sylius_gallery:
            filters:
                thumbnail: { size: [640, 480], mode: outbound }

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/wkhtmltoimage
        options:    []

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.block.service.text:

cmf_core:
    publish_workflow: false

cmf_block:
    persistence:
        phpcr:
            block_basepath: /cms/blocks

cmf_content:
    persistence:
        phpcr:
            content_basepath: /cms/pages

cmf_routing:
    dynamic:
        generic_controller: cmf_content.controller:indexAction
        persistence:
            phpcr: ~

sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Tresepic\BoprBundle\Entity\Product
            form: Tresepic\BoprBundle\Form\Type\ProductType
            
sylius_resource:
    resources:
        bopr.manufacturer:
            driver: doctrine/orm
            classes:
                model: Tresepic\BoprBundle\Entity\Manufacturer
                controller: Tresepic\BoprBundle\Controller\Backend\ManufacturerController
                
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~
    
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                product:
                    mappings:
                        name: ~
                        description: ~
                    persistence:
                        driver: orm
                        model: Tresepic\BoprBundle\Entity\Product
                        provider: ~
                        finder: ~
                        
a2lix_translation_form:
    locales: [en, es]