sylius_installer:
    resource: @SyliusInstallerBundle/Resources/config/routing.yml

sylius_web:
    resource: @SyliusWebBundle/Resources/config/routing/main.yml

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_registration_register:
    pattern: /register/
    defaults: { _controller: TresepicBoprBundle:Registration:register }
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

twitter_login:
    pattern: /login/check-twitter

tresepic_bopr_backend:
    resource: @TresepicBoprBundle/Resources/config/routing/backend/manufacturer.yml
    prefix: /administration/manufacturer

sylius_newsletter:
    pattern: /newsletter
    defaults: { _controller: sylius.controller.frontend.homepage:newsletterAction }
    methods:  [POST]
    
sylius_search:
    pattern: /search
    defaults: { _controller: sylius.controller.frontend.homepage:searchAction }
    methods:  [POST]
    