# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_partial_product_latest:
    pattern: /latest
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            paginate: false
            method: findLatest
            arguments: [$limit]
            template: $template
            
sylius_partial_product_random:
    pattern: /random
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            paginate: false
            method: findRandom
            arguments: [$limit]
            template: $template
