# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_homepage:
    pattern: /
    defaults: { _controller: sylius.controller.frontend.homepage:mainAction }

sylius_masacote:
    pattern: /masacote
    defaults: { _controller: sylius.controller.frontend.homepage:masacoteAction }

sylius_yoapoyoajulia:
    pattern: /yoapoyoajulia
    defaults: { _controller: sylius.controller.frontend.homepage:yoapoyoajuliaAction }

bopr_subscription:
    pattern: /subscriptions
    defaults: { _controller: sylius.controller.frontend.homepage:subscriptionAction }

bopr_services:
    pattern: /services
    defaults: { _controller: sylius.controller.frontend.homepage:servicesAction }
    
bopr_services_send_mail:
    pattern: /services/send-mail
    defaults: { _controller: sylius.controller.frontend.homepage:servicesSendMailAction }
                
sylius_currency:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/currency.yml
    prefix: /currency

sylius_product:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/product.yml

sylius_page:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/page.yml
    prefix: /content

sylius_checkout:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/checkout.yml
    prefix: /checkout

sylius_account:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/account.yml
    prefix: /account

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

sylius_cart_summary:
    pattern: /cart
    defaults:
        _controller: sylius.controller.cart:summaryAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig

sylius_cart_save:
    pattern: /cart/save
    defaults:
        _controller: sylius.controller.cart:saveAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig
