parameters:
    sylius.menu_builder.backend.class: Tresepic\BoprBundle\Menu\BackendMenuBuilder

services:
    bopr.form.type.manufacturer:
        class: Tresepic\BoprBundle\Form\Type\ManufacturerType
        tags:
            - { name: form.type, alias: bopr_manufacturer }
            
    bopr.locale_listener:
        class: Tresepic\BoprBundle\EventListener\LocaleListener
        arguments: [@service_container, "%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    bopr.send.mailer:
        class: Tresepic\BoprBundle\Mailer\SendMailer
        arguments: ["@service_container"]