parameters:
    sylius.menu_builder.backend.class: Tresepic\BoprBundle\Menu\BackendMenuBuilder
    sylius.shipping_calculator.usps.class: Tresepic\BoprBundle\Shipping\Calculator\USPSCalculator

services:
    bopr.form.type.manufacturer:
        class: Tresepic\BoprBundle\Form\Type\ManufacturerType
        tags:
            - { name: form.type, alias: bopr_manufacturer }
            
    bopr.locale_listener:
        class: Tresepic\BoprBundle\EventListener\LocaleListener
        arguments: [@service_container, "%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    bopr.send.mailer:
        class: Tresepic\BoprBundle\Mailer\SendMailer
        arguments: ["@service_container"]
        
    sylius.shipping_calculator.usps:
        class: "%sylius.shipping_calculator.usps.class%"
        tags:
            - { name: "sylius.shipping_calculator", calculator: "usps", label: "USPS Calculator" }
            
    bopr.validator.usps_address_validator:
        class: Tresepic\BoprBundle\Validator\Constraints\USPSAddressValidator
        arguments: [@sylius.shipping_calculator.usps]
        tags:
            - { name: validator.constraint_validator, alias: usps_address_validator }