# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_order_history_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Order:history.html.twig
            method: createFilterPaginator
            arguments: [$criteria, $sorting, true]
            paginate: 20

backend_order_history_download_excel:
    path:     /download_excel
    defaults:
        _controller: sylius.controller.order:downloadExcelAction
        _sylius:
            method: createFilterPaginator
            arguments: [$criteria, $sorting, true]
            paginate: 99999999999999999999